version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=868240383494.dkr.ecr.sa-east-1.amazonaws.com/mssc-beer-inventory-service
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      # - IMAGE_TAG=${COMMIT_HASH:=latest}
      - IMAGE_TAG=latest
  build:
    commands:
      - mvn clean install -DskipTests
      - echo Build started on `date`
      - echo Building the Docker image...
      # - docker build -t $REPOSITORY_URI:latest . --no-cache
      # - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - mvn docker:build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      # - docker push $REPOSITORY_URI:latest
      # - docker push $REPOSITORY_URI:$IMAGE_TAG
      - mvn docker:push
      - echo Writing image definitions file...
      - printf '[{"name":"mssc-beer-inventory-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: 
      # - target/mssc-beer-inventory-service-0.0.1-SNAPSHOT.jar
      - imagedefinitions.json
      - Dockerrun.aws.json
deploy:
    artifact: Dockerrun.aws.json

cache:
  paths:
    - '/root/.m2/**/*'